#! /usr/bin/env python3

# Note: Ensure that the user running this script is a member of the `gpio` group.

import Adafruit_DHT

DHT_SENSOR = Adafruit_DHT.DHT22
DHT_PIN = 4

while True:
    humidity, temperature = Adafruit_DHT.read_retry(
        DHT_SENSOR, DHT_PIN, retries=3, delay_seconds=2
    )

    if humidity is not None and temperature is not None:
        print("Temp={0:0.1f}*C Humidity={1:0.1f}%".format(temperature, humidity))
    else:
        print("Failed to retrieve data from humidity sensor.")
